require("items.widgets.battery")
require("items.widgets.volume")
require("items.widgets.wifi")
require("items.widgets.cpu")
require("items.widgets.memory")
require("items.widgets.pomodoro")
require("items.widgets.meetingbar")
