#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

yabai -m config external_bar all:$(sketchybar --query bar | jq .height):0 \
                layout                     bsp            \
                mouse_follows_focus        on             \
                focus_follows_mouse        off            \
                window_zoom_persist        off            \
                window_origin_display      default        \
                window_placement           second_child   \
                window_topmost             off            \
                window_shadow              on             \
                window_opacity             off            \
                window_opacity_duration    0.2            \
                active_window_opacity      1.0            \
                normal_window_opacity      0.8            \
                window_animation_duration  0.1            \
                window_animation_easing    ease_out_quint \
                insert_feedback_color      0xff9dd274     \
                split_ratio                0.66           \
                auto_balance               on             \
                mouse_modifier             alt            \
                mouse_action1              move           \
                mouse_action2              resize         \
                mouse_drop_action          swap           \
                                                          \
                top_padding                2              \
                bottom_padding             2              \
                left_padding               2              \
                right_padding              2              \
                window_gap                 3

yabai -m signal --add app='^Ghostty$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add app='^Ghostty$' event=window_destroyed action='yabai -m space --layout bsp'

yabai -m rule --add app=".*" sub-layer=normal

# apps to not manage (ignore)
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Stickies$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^eqMac$" manage=off
yabai -m rule --add app="^borders$" manage=off
yabai -m rule --add app="^Cisco AnyConnect Secure Mobility Client$" manage=off
yabai -m rule --add app="^Amazon Chime$" manage=off
yabai -m rule --add title="^Picture in Picture$" manage=off
yabai -m rule --add title="^Picture-in-Picture$" manage=off
yabai -m rule --add title="^Amazon Chime: Meeting Controls$" manage=off
yabai -m rule --add title="^Amazon Chime: Screen Share Border$" manage=off
yabai -m rule --add title="^Amazon Chime: Screen Share Border$" manage=off
# yabai -m rule --add title="^$" manage=off

# borders active_color=0xe1f1e100 inactive_color=0xff494d64 width=15.0 &

echo "yabai configuration loaded.."
