require("items.apple")
require("items.menus")
require("items.spaces")  -- Workspace display (backend-agnostic via items.wm)
require("items.front_app")
require("items.calendar")
require("items.widgets")
require("items.media")