#### DYNAMIC ISLAND USER CONFIG - MACBOOK PRO M4 MAX 16 INCH #####

## Customized for MacBook Pro 16" (Mac16,5) with M4 Max

#
### Main config
#

# Which display should the dynamic island be available?
# Available options: all, main, id of display (e.g. 1, 2, 3)
P_DYNAMIC_ISLAND_DISPLAY=main

# Needs to have Regular, Bold, Semibold, Heavy and Black variants
P_DYNAMIC_ISLAND_FONT="SF Pro"

# Enable/Disable Islands
P_DYNAMIC_ISLAND_MUSIC_ENABLED=1
P_DYNAMIC_ISLAND_APPSWITCH_ENABLED=1
export P_DYNAMIC_ISLAND_NOTIFICATION_ENABLED=0
P_DYNAMIC_ISLAND_VOLUME_ENABLED=1
P_DYNAMIC_ISLAND_BRIGHTNESS_ENABLED=1
P_DYNAMIC_ISLAND_WIFI_ENABLED=1
P_DYNAMIC_ISLAND_POWER_ENABLED=1

# Notch Size (slightly larger for 16")
P_DYNAMIC_ISLAND_DEFAULT_HEIGHT=46
P_DYNAMIC_ISLAND_DEFAULT_WIDTH=105
P_DYNAMIC_ISLAND_CORNER_RADIUS=11

# MacBook Pro 16" has 3456x2234 resolution, so 3456/2=1728
P_DYNAMIC_ISLAND_MONITOR_HORIZONTAL_RESOLUTION=1728

# Animation Settings
P_DYNAMIC_ISLAND_SQUISH_AMOUNT=6


#
## App Switch Island config
#
P_DYNAMIC_ISLAND_APPSWITCH_MAX_EXPAND_WIDTH=115
P_DYNAMIC_ISLAND_APPSWITCH_EXPAND_HEIGHT=58
P_DYNAMIC_ISLAND_APPSWITCH_CORNER_RAD=16
P_DYNAMIC_ISLAND_APPSWITCH_ICON_SIZE=1


#
## Volume Island config
#
P_DYNAMIC_ISLAND_VOLUME_MAX_EXPAND_WIDTH=135
P_DYNAMIC_ISLAND_VOLUME_EXPAND_HEIGHT=68
P_DYNAMIC_ISLAND_VOLUME_CORNER_RAD=13
P_DYNAMIC_ISLAND_VOLUME_NORMAL_ICON_COLOR=0xffffffff
P_DYNAMIC_ISLAND_ICON_VOLUME_MAX=􀊩
P_DYNAMIC_ISLAND_ICON_VOLUME_MED=􀊧
P_DYNAMIC_ISLAND_ICON_VOLUME_LOW=􀊥
P_DYNAMIC_ISLAND_ICON_VOLUME_MUTED=􀊡

#
## Brightness Island config
#
P_DYNAMIC_ISLAND_BRIGHTNESS_MAX_EXPAND_WIDTH=135
P_DYNAMIC_ISLAND_BRIGHTNESS_EXPAND_HEIGHT=68
P_DYNAMIC_ISLAND_BRIGHTNESS_CORNER_RAD=13
P_DYNAMIC_ISLAND_BRIGHTNESS_NORMAL_ICON_COLOR=0xffffffff
P_DYNAMIC_ISLAND_ICON_BRIGHTNESS_LOW=􀆫
P_DYNAMIC_ISLAND_ICON_BRIGHTNESS_HIGH=􀆭


#
## Music Island config
#
# Music Info - Use Spotify if you prefer
P_DYNAMIC_ISLAND_MUSIC_SOURCE="Music"
P_DYNAMIC_ISLAND_MUSIC_INFO_MAX_EXPAND_WIDTH=175
P_DYNAMIC_ISLAND_MUSIC_INFO_EXPAND_HEIGHT=105
P_DYNAMIC_ISLAND_MUSIC_INFO_CORNER_RAD=20

# Music Idle Info
P_DYNAMIC_ISLAND_MUSIC_IDLE_EXPAND_WIDTH=165

# Resume Info
P_DYNAMIC_ISLAND_MUSIC_RESUME_MAX_EXPAND_WIDTH=160
P_DYNAMIC_ISLAND_MUSIC_RESUME_EXPAND_HEIGHT=58
P_DYNAMIC_ISLAND_MUSIC_RESUME_CORNER_RAD=16

#
## WIFI Island config
#
P_DYNAMIC_ISLAND_WIFI_MAX_EXPAND_WIDTH=195
P_DYNAMIC_ISLAND_WIFI_EXPAND_HEIGHT=58
P_DYNAMIC_ISLAND_WIFI_CORNER_RAD=16
P_DYNAMIC_ISLAND_ICON_WIFI_CONNECTED=􀙇
P_DYNAMIC_ISLAND_ICON_WIFI_DISCONNECTED=􀙈

#
## Battery Island config
#
P_DYNAMIC_ISLAND_BATTERY_MAX_EXPAND_WIDTH=195
P_DYNAMIC_ISLAND_BATTERY_EXPAND_HEIGHT=58
P_DYNAMIC_ISLAND_BATTERY_CORNER_RAD=16
P_DYNAMIC_ISLAND_ICON_BATTERY_CONNECTEDAC=􀢋
P_DYNAMIC_ISLAND_ICON_BATTERY_ONBATTERY=􀺸


#
## Notification Island Config
#
P_DYNAMIC_ISLAND_NOTIFICATION_MAX_EXPAND_WIDTH=185
P_DYNAMIC_ISLAND_NOTIFICATION_EXPAND_HEIGHT=95
P_DYNAMIC_ISLAND_NOTIFICATION_CORNER_RAD=44
P_DYNAMIC_ISLAND_NOTIFICATION_MAX_ALLOWED_BODY=250

############# THESE VALUES SHOULDN'T BE TOUCHED #############

#
## Colors
#
P_DYNAMIC_ISLAND_COLOR_WHITE=0xffffffff
P_DYNAMIC_ISLAND_COLOR_BLACK=0xff000000
P_DYNAMIC_ISLAND_COLOR_TRANSPARENT=0x00000000
P_DYNAMIC_ISLAND_COLOR_ICON_HIDDEN=$P_DYNAMIC_ISLAND_COLOR_BLACK
